scheme="http" # GitLab URL Scheme
host="localhost:10080" # GitLab Hostname
user="USER" # GitLab User
pass="PASSWORD" # GitLab Password
branch="master" # GitLab target branch
privateToken="TOKEN" # GitLab PrivateToken (Read more https://docs.gitlab.com/ce/api/README.html#private-tokens )
outDir="./" # GitLab Repositories output directory
