gitlabApiUrl="https://{host}" # GitLab API URL
privateToken="{token}" # GitLab PrivateToken (Read more https://docs.gitlab.com/ce/api/README.html#private-tokens )
gitlabSshUrl="ssh://git@{host}:{port}" # GitLab SSH URL
branch="master" # GitLab target branch
outDir="{fullpath}" # GitLab Repositories output directory
filterInNameSpace="{namespace}"
filterOutProject="{out1},{out2},{out3}"