gitlabApiUrl="http://localhost:10080" # GitLab API URL
privateToken="token" # GitLab PrivateToken (Read more https://docs.gitlab.com/ce/api/README.html#private-tokens )
gitlabSshUrl="ssh://git@localhost:10022" # GitLab SSH URL
outDir="/tmp" # GitLab Repositories output directory
